apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: postgres-postgis
  namespace: pg-postgis
spec:
  version: "11.7-postgis" # points to the name of our custom PostgresVersion
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi